name: .NET Framework Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore UnitTestProject3/UnitTestProject3/UnitTestProject3.csproj

    - name: Build
      run: msbuild UnitTestProject3/UnitTestProject3/UnitTestProject3.csproj /p:Configuration=Release

    - name: Run Tests
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" UnitTestProject3/UnitTestProject3/bin/Release/UnitTestProject3.dll
