name: .NET Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet
      run: nuget restore UnitTestProject3.sln

    - name: Build
      run: msbuild UnitTestProject3.sln /p:Configuration=Release /p:Platform="AnyCPU"

    - name: Run Tests
      run: vstest.console.exe **\bin\Release\UnitTestProject3.dll
