name: .NET Tests

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore UnitTestProject3/UnitTestProject3/UnitTestProject3.csproj

    - name: Build
      run: dotnet build UnitTestProject3/UnitTestProject3/UnitTestProject3.csproj --no-restore

    - name: Test
      run: dotnet test UnitTestProject3/UnitTestProject3/UnitTestProject3.csproj --no-build --verbosity normal
